# Generated by Django 5.1.1 on 2024-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='content',
            field=models.TextField(),
        ),
    ]
