# Generated by Django 5.1.1 on 2024-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_core_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(help_text='Maximum of 150 charcters', max_length=150, verbose_name='Title of the core'),
        ),
    ]
