# Generated by Django 5.1.1 on 2024-11-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text=' Maximum of 150 characters', max_length=150, verbose_name='Title of the  author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('about', models.TextField(blank=True, help_text='Max 1000 characters', null=True, verbose_name='About of product')),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'All Description',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 characters', max_length=100, verbose_name='Title of the product')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'All Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum of 150 charcters', max_length=150, verbose_name='Title of the product')),
                ('content', models.TextField(verbose_name='Content of the product')),
                ('product_types', models.IntegerField(choices=[(0, 'Choose'), (1, 'Tech'), (2, 'Food'), (3, 'Travel'), (4, 'Lifestyle')], default=0, verbose_name='Type of the product')),
                ('is_check', models.BooleanField(default=False, verbose_name='Check if the product is published')),
                ('cover_image', models.ImageField(blank=True, help_text='Upload a cover image for the product', null=True, upload_to='product/', verbose_name='Cover Image of the  product ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productauthor', to='product.author', verbose_name='Author of the product')),
                ('tags', models.ManyToManyField(related_name='producttags', to='product.tags', verbose_name='Tags of the product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
    ]
