# Generated by Django 5.1.1 on 2024-11-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the product', null=True, upload_to='product', verbose_name='Cover Image of the  product '),
        ),
    ]
