# Generated by Django 5.1.1 on 2024-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
