# Generated by Django 5.1.1 on 2024-10-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogauthor', to='blog.author', verbose_name='Author of the blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogdescription', to='blog.description', verbose_name='Description of the blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.ManyToManyField(related_name='blogtags', to='blog.tags', verbose_name='Tags of the blog'),
        ),
    ]
