# Generated by Django 5.1.1 on 2024-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_author_alter_blogs_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the blog', null=True, upload_to='blog/', verbose_name='Cover Image of the  blog '),
        ),
    ]
