# Generated by Django 5.1.1 on 2024-10-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blod_types',
            new_name='blog_types',
        ),
    ]
