# Generated by Django 5.1.1 on 2024-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogs_description_remove_blogs_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='Check if the blog is published'),
        ),
    ]
