# Generated by Django 5.1.1 on 2024-11-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogs_is_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for the blog', null=True, upload_to='blog', verbose_name='Cover Image of the  blog '),
        ),
    ]
