# Generated by Django 5.1.1 on 2024-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogs_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='cover_image',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog'),
        ),
    ]
